export const prix_noms = [
    `accessit`,
    `accessit 1`,
    `accessit 2`,
    `accessit 3`,
    `accessit 4`,
    `accessit 5`,
    `accessit 6`,
    `legs et donations`,
    `mention`,
    `mention 1`,
    `mention 2`,
    `mention 3`,
    `mention d'encouragement 1`,
    `mention honorable`,
    `médaille`,
    `médaille 1`,
    `médaille 2`,
    `médaille 3`,
    `prix 1`,
    `prix 2`,
    `prix d'honneur`,
    `prix d'honneur 1`,
]